# Generated by Django 4.1.2 on 2022-11-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
                ('text', models.TextField(blank=True, verbose_name='Текст статьи')),
                ('date', models.DateField(verbose_name='Дата публикации')),
                ('is_main_page', models.BooleanField(default=False, verbose_name='Главная страница?')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опублковать?')),
                ('preview_photo', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Фото превью')),
            ],
            options={
                'verbose_name': 'Статьи',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-date', 'title'],
            },
        ),
    ]
